# Generated by Django 4.2.1 on 2023-07-31 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_profile_revenue', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_profile_revenue', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('discount_profile_type', models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Editor', 'Editor'), ('Pilot', 'Pilot')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)])),
                ('order_type', models.CharField(choices=[('Letter', 'Letter'), ('Parcel', 'Parcel'), ('Box', 'Box')], max_length=6)),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='PricesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.PositiveIntegerField()),
                ('max_weight', models.PositiveIntegerField()),
                ('price_per_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('target_order_type', models.CharField(choices=[('Letter', 'Letter'), ('Parcel', 'Parcel'), ('Box', 'Box')], max_length=6)),
            ],
        ),
    ]
