# Generated by Django 4.2.1 on 2023-07-22 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Operational', '0003_alter_flightmodel_flight_status'),
        ('UserAccount', '0004_alter_droneboxprofile_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_profile_revenue', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_profile_revenue', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('discount_profile_type', models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Editor', 'Editor'), ('Pilot', 'Pilot')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PricesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.PositiveIntegerField()),
                ('max_weight', models.PositiveIntegerField()),
                ('price_per_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('target_order_type', models.CharField(choices=[('Letter', 'Letter'), ('Parcel', 'Parcel'), ('Box', 'Box')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('order_type', models.CharField(choices=[('Letter', 'Letter'), ('Parcel', 'Parcel'), ('Box', 'Box')], max_length=6)),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Pending', max_length=9)),
                ('order_flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Operational.flightmodel')),
                ('order_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserAccount.droneboxprofile')),
                ('order_route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Operational.routesmodel')),
            ],
        ),
    ]
