# Generated by Django 4.2.1 on 2023-07-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operational', '0003_alter_flightmodel_flight_status'),
        ('Commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='order_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Operational.flightmodel'),
        ),
    ]
