# Generated by Django 4.2.1 on 2023-07-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_alter_droneboxprofile_profile_type'),
        ('Commercial', '0002_alter_ordersmodel_order_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='order_profile',
            field=models.ForeignKey(on_delete=models.SET('to_be_deleted'), to='UserAccount.droneboxprofile'),
        ),
    ]
