# Generated by Django 4.2.1 on 2023-07-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_alter_droneboxprofile_profile_type'),
        ('Commercial', '0004_alter_ordersmodel_order_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='order_profile',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='UserAccount.droneboxprofile'),
            preserve_default=False,
        ),
    ]
