# Generated by Django 4.2.1 on 2023-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commercial', '0006_alter_ordersmodel_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=9),
        ),
    ]
