# Generated by Django 4.2.1 on 2023-07-31 06:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=50)),
                ('iata_code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('operational_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fuel_cost', models.FloatField(blank=True, default=2.15, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='DroneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('mtow', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9000000)])),
                ('range', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9000000)])),
                ('fuel_burn_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9000000)])),
            ],
        ),
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('flight_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('flight_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='RoutesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_capacity', models.FloatField(editable=False, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('current_capacity', models.FloatField(blank=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('distance', models.FloatField(editable=False, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Route_Destination_Airport', to='Operational.airportmodel')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Route_Origin_Airport', to='Operational.airportmodel')),
                ('route_drone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Operational.dronemodel')),
            ],
        ),
    ]
