# Generated by Django 4.2.1 on 2023-07-31 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAccount', '0001_initial'),
        ('Operational', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightmodel',
            name='drone_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserAccount.droneboxprofile'),
        ),
        migrations.AddField(
            model_name='flightmodel',
            name='flight_destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Flight_Destination_Airport', to='Operational.airportmodel'),
        ),
        migrations.AddField(
            model_name='flightmodel',
            name='flight_drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Operational.dronemodel'),
        ),
        migrations.AddField(
            model_name='flightmodel',
            name='flight_origin_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Flight_Origin_Airport', to='Operational.airportmodel'),
        ),
    ]
