# Generated by Django 4.2.1 on 2023-07-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operational', '0002_alter_routesmodel_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='flight_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=9),
        ),
    ]
