# Generated by Django 4.2.1 on 2023-07-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operational', '0003_alter_flightmodel_flight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesmodel',
            name='destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Route_Destination_Airport', to='Operational.airportmodel'),
        ),
        migrations.AlterField(
            model_name='routesmodel',
            name='origin_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Route_Origin_Airport', to='Operational.airportmodel'),
        ),
        migrations.AlterField(
            model_name='routesmodel',
            name='route_drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Operational.dronemodel'),
        ),
    ]
