# Generated by Django 4.2.1 on 2023-07-29 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operational', '0004_alter_routesmodel_destination_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronemodel',
            name='fuel_burn_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9000000)]),
        ),
        migrations.AlterField(
            model_name='dronemodel',
            name='mtow',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9000000)]),
        ),
        migrations.AlterField(
            model_name='dronemodel',
            name='range',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9000000)]),
        ),
    ]
