# Generated by Django 4.2.1 on 2023-07-30 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operational', '0005_alter_dronemodel_fuel_burn_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportmodel',
            name='fuel_cost',
            field=models.FloatField(blank=True, default=2.15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
