# Generated by Django 4.2.1 on 2023-07-30 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_alter_droneboxprofile_profile_type'),
        ('Operational', '0006_airportmodel_fuel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightmodel',
            name='drone_operator',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.DO_NOTHING, to='UserAccount.droneboxprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='flight_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=9),
        ),
    ]
