# Generated by Django 4.2.1 on 2023-07-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.FloatField(blank=True, default=0)),
                ('revenue', models.FloatField(blank=True, default=0)),
                ('expenses', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=30)),
                ('article_content', models.TextField()),
                ('article_author', models.CharField(max_length=30)),
                ('article_author_key', models.BigIntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
