# Generated by Django 4.2.1 on 2023-07-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Customer', 'Customer'), ('Editor', 'Editor'), ('Pilot', 'Pilot')], max_length=8)),
            ],
        ),
    ]
