# Generated by Django 4.2.1 on 2023-07-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_testmodel_distance_typesmodel_distance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.DeleteModel(
            name='TypesModel',
        ),
    ]
