# Generated by Django 4.2.1 on 2023-07-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='article_author_key',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
