# Generated by Django 4.2.1 on 2023-07-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0006_newsmodel_article_author_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.FloatField(blank=True, default=0)),
                ('revenue', models.FloatField(blank=True, default=0)),
                ('expenses', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
